### ISSUE TITLE
Error while parsing GS1 barcode

### ISSUE THREAD

**Issue by klausmcm** [jodal/biip#137]
Hello, I tried parsing the data from the following barcode (data is `1021072911172405310100693570007182` and does not include any separator/FNC1 characters) and received a `ParseError`

![IMG_20220331_173635](https://user-images.githubusercontent.com/14914359/161208508-29194ebc-a818-4eb3-812a-06c50dc230e5.jpg)

The data should be the following: `(10)21072911(17)240531(01)00693570007182` (lot, expiry, GTIN)

I'm aware that ai 10 (lot) can vary in length so I wanted to check my understanding and confirm that this is not an issue with `biip`. Has this barcode not been constructed properly?

Thank you,

**Comment by jodal** [comment]
First of all, thank you for including a photo in the issue. It makes things so much more concrete and easier to debug!

If this was a one dimensional barcode, like GS1-128, I'd scan the barcode with a phone app that shows FNC1 separators (I'm using Cognex Barcode Scanner on Android). If it showed an FNC1 separator, I'd say that the issue was with your scanner's configuration, and that you need to configure it to give you a special character where there's a FNC1 separator, so that Biip could know about the FNC1's placement. If the phone app showed no FNC1 separator, I'd say the problem was with the production of the barcode.

I'm not as familiar with GS1 AI strings in Datamatrix barcodes, so I don't know without researching a bit if these also should use FNC1 or if they have some other replacement. The GS1 General Specification probably has the details here. Either way, the end of the variable length fields needs to be communicated to the scanning application *in some way* for the application to be able to correctly interpret the data. What I know is that the phone app I usually test with shows no FNC1 separator (usually shown by a space) here. Thus, I'm thinking that this barcode is either broken, or there is another solution for variable-length field separators in Datamatrix barcodes that my phone app doesn't support.

**Comment by jodal** [comment]
Quoting [GS1 General Specification](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf), section 5.6.2 GS1 DataMatrix features and symbol basics:

> Data Matrix ISO version ECC 200 is the only version that supports GS1 system data structures,
including Function 1 Symbol Character (FNC1).

...

> FNC1 for GS1 system compatibility SHALL be encoded at the beginning of the data string. **When
a separator character is needed** at the end of an element string, either the Function 1 Symbol
Character (FNC1) or the control character <GS> (ASCII value 29 (decimal), 1D (hexadecimal))
SHALL be used and SHALL be represented in the transmitted message by control character
<GS> (ASCII value 29 (decimal), 1D (hexadecimal)).

This is a screenshot from the [GS1 DataMatrix Guideline](https://www.gs1.org/docs/barcodes/GS1_DataMatrix_Guideline.pdf), section 2.3:

![screenshot_2022-04-01_15-00-11](https://user-images.githubusercontent.com/43726/161268490-e919bcde-8cf0-4699-b38b-9ef3afb9bd51.png)

This is a GS1 DataMatrix barcode with an FNC1 marking the end of a variable-length lot number. Scanning this with my phone app, a space character shows up where the FNC1 is supposed to be.

However, the space character *does not* show up when scanning the barcode with a variable-length lot number in your photo. 

To me, this is a strong indication of your barcode is actually missing the required FNC1 markers.

**Comment by klausmcm** [comment]
@jodal Thank you for the detailed response. This is great! I also suspected that there's an issue with the barcode. The barcode is from a commercial setting and I get suspicious when an issue like this occurs believing that the industry would not make such mistakes. In case you're curious, here's another barcode with FNC1 characters. I had the foresight to include the encoded text in the same photo.

![IMG_20220326_214118](https://user-images.githubusercontent.com/14914359/161298720-832811c7-6cf0-4314-8f6c-0b8ba20fc65b.jpg)

I use https://github.com/markusfisch/BinaryEye on my phone for scanning and save the text to file and read the contents of that file into `biip` which does properly parse the pieces of information.

[IMG_20220326_214118.txt](https://github.com/jodal/biip/files/8399228/IMG_20220326_214118.txt)

![Screenshot_20220401-084436](https://user-images.githubusercontent.com/14914359/161298927-d8f26053-d071-48d0-8221-bc6382e77495.png)

Thank you for this package.

**Comment by jodal** [comment]
That looks like a very useful app, to get the data on byte level!

Just a final note: I'd love if you/your company as a user of Biip added yourself to https://github.com/jodal/biip/wiki/Users

**Comment by klausmcm** [comment]
For sure, let me get back to you next week. Just need to try out a few things first.
